name: Create Components

on:
  push:
    branches:
      - main  # Runs when pushing to the 'main' branch
  workflow_dispatch:  # Allows manual trigger in GitHub Actions

jobs:
  create-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          pwsh ./scripts/CreateComponents.ps1
